name: Node Build Format Test Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.1        
      - name: Install dependencies
        run: npm install
      - name: Run format script
        run: npm run format
      - name: Run tests
        run: npm test 
